### ISSUE TITLE
NameError: name 'df' is not defined

### ISSUE THREAD

**Issue by omkarmohanjoshi** [omkarmohanjoshi/Brain_Tumor_Classification#1]
```
Traceback (most recent call last):
  File "src/train.py", line 47, in <module>
    main(repo_path)
  File "src/train.py", line 39, in main
    train_data, labels = load_data(train_csv_path)
  File "src/train.py", line 30, in [load_data](url)
    labels = load_labels(data_frame=df, column_name="label")
NameError: name 'df' is not defined

```

**Comment by omkarmohanjoshi** [comment]
df is missing
